// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7AhzieT_1_ALpibioF4mn3h-Hj9vFKI',
    appId: '1:925890560315:web:e51798c963ac1a5519371e',
    messagingSenderId: '925890560315',
    projectId: 'campus-event-board-1f634',
    authDomain: 'campus-event-board-1f634.firebaseapp.com',
    databaseURL: 'https://campus-event-board-1f634-default-rtdb.firebaseio.com',
    storageBucket: 'campus-event-board-1f634.firebasestorage.app',
    measurementId: 'G-5E086XPNYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALM90wGV3sB9r1-W48fqZewiQGEtlirIU',
    appId: '1:925890560315:android:6acc9a4f93edb65a19371e',
    messagingSenderId: '925890560315',
    projectId: 'campus-event-board-1f634',
    databaseURL: 'https://campus-event-board-1f634-default-rtdb.firebaseio.com',
    storageBucket: 'campus-event-board-1f634.firebasestorage.app',
  );
}
